version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2
    steps:
      - checkout
      - run: ./install.sh

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install .
            pip install pylint
            pylint target_snowflake -d C,W,unexpected-keyword-arg,duplicate-code
   
      - run:
          name: 'Unit Tests'
          command: |
            . venv/bin/activate
            pip install nose
            nosetests --where=tests/unit

      - run:
          name: 'Integration Tests'
          command: |
            . venv/bin/activate
            pip install nose
            nosetests --where=tests/integration/

workflows:
  version: 2
  build:
    jobs:
      - build
